#!/bin/bash

function dev-mysql-ha-init() {

  if [ ! -z "$BAIDS_DEBUG" ]
  then
    set -x
  else
    set +x
  fi

  export PROJECT_DIR="$( dirname $(readlink -f $(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ) ) )"
  export INFRASTRUCTURE_DIR="$PROJECT_DIR/infrastructure"
  export DATA_DIR="$PROJECT_DIR/data"
  export DOCKER_COMPOSE_FILE="$INFRASTRUCTURE_DIR/docker-compose.yml"

  export HAPROXY_DOCKER_IMAGE="tutum/haproxy:latest"
  export MYSQL_CLUSTER_DOCKER_IMAGE="mysql/mysql-cluster:latest"

  export MYSQL_ROOT_PASSWORD="1234"
  export MYSQL_DATABASE="prueba"
  export MYSQL_ROOT_HOST="%"


}
